### ISSUE TITLE
Nomad download & unzip fails

### ISSUE THREAD

**Issue by lukaszkorecki** [kbrebanov/ansible-nomad#14]
I'm currently evaluating nomad and this role looked the best to get the job done fast - thank you for creating it 👍 

I've run into an issue though - our machines never access 'root' user and we have a special user which can do certain things which are permitted via sudo.
Given that:
- for some reason I can't override `nomad_download_dir` to `/tmp`
- when doing it by hand I'm running into permission errors because `become: true` [is set in the download and unzip tasks](https://github.com/kbrebanov/ansible-nomad/blob/master/tasks/main.yml#L24) 

Is there any reason for using root user here? Feels like always downloading to tmp or ~ of the current user would do the trick.

Happy to send a PR which addresses this issue, but it's always better to check first ;-) - I might be missign something.
 
Thanks

**Comment by kbrebanov** [comment]
I chose not to use `/tmp` because the file would get deleted on reboots. It needs to stay in the directory for the role to be idempotent. I also didn't chose `~` as that would mean that the file could end up at different locations on systems that are provisioned with a different user.

So, you can't override the variable because it's under the `vars` directory. You can simply move that variable to defaults and update the README accordingly, then you will be able to set it to what you want.

The `become` directive is used on tasks that require elevated privileges to complete.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
